spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-springcloud-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-springcloud-test
